name: Deploy React App to EC2

on:
  push:
    branches:
      - main  # Deploy when you push to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # Run on an Ubuntu runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'  # Set your preferred Node.js version

    - name: Install dependencies
      run: |
        npm install  # Install dependencies

    - name: Build the React app
      run: |
        npm run build  # Generates the 'build' folder

    - name: Verify build folder existence
      run: |
        ls -l ./build  # Debug: Verify that the build folder exists

    - name: Deploy to EC2 via SSH
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
        EC2_IP: ${{ secrets.EC2_IP }}
      run: |
        # Create the SSH directory and save the private key
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

        # Add the EC2 instance to known hosts to avoid SSH verification
        ssh-keyscan -H $EC2_IP >> ~/.ssh/known_hosts

        # Verify the build folder exists
        ls -l ./build  # Check if the build folder exists

        # Copy the build folder to the EC2 instance
        scp -r ./build $EC2_USERNAME@$EC2_IP:/home/ubuntu/first-react-app

        # SSH into the EC2 instance and configure Nginx
        ssh -o StrictHostKeyChecking=no $EC2_USERNAME@$EC2_IP << 'EOF'
          # Update and install Nginx (if not already installed)
          sudo apt-get update -y
          sudo apt-get install -y nginx

          # Remove default files from Nginx directory
          sudo rm -rf /var/www/html/*

          # Copy new build files from first-react-app folder to Nginx folder
          sudo cp -r /home/ubuntu/first-react-app/build/* /var/www/html/

          # Set ownership and permissions for the files
          sudo chown -R www-data:www-data /var/www/html/
          sudo chmod -R 755 /var/www/html/

          # Update Nginx config for React routing
          sudo bash -c 'cat > /etc/nginx/sites-available/default' << 'EOF2'
            server {
                listen 80 default_server;
                listen [::]:80 default_server;

                root /var/www/html;
                index index.html;

                server_name _;  # Default catch-all

                location / {
                    try_files $uri /index.html =404;
                }
            }
          EOF2

          # Restart Nginx to apply the new configuration
          sudo systemctl restart nginx
        EOF
